blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://camunda-platform.slack.com/archives/C0497FR8XML
    about: Head over to our slack channel to ask questions and get answers.